Api/01
aurelienCastellarnau/mean pull request #4
Opened 2017-05-13 13:33 UTC by Kumatetsu

2017-05-13 15:12 UTC, aurelienCastellarnau reviewed
C'est bon pour moi jusque là. Je comprend se qui se passe.

2017-05-13 15:12 UTC, aurelienCastellarnau commented on api.js
> +      app          = module.exports = express(),
ça fait quoi çaaa?

2017-05-14 14:43 UTC, aurelienCastellarnau commented on routes/cases.js
> +            // c'est dégueulasse, faut que je change ça en fonction intelligente /!\
for(var key in case){
    case[key] = req.body[key] || case[key]
}

2017-05-14 15:18 UTC, Kumatetsu commented on api.js
> +      app          = module.exports = express(),
petit tricks magique. après tu fais un require sur app.js et tu récupères ta session de express #abus

2017-05-14 15:32 UTC, aurelienCastellarnau requested changes

2017-05-14 15:32 UTC, aurelienCastellarnau commented on routes/cases.js
> +    let case
Conflit de nommage entre cette variable et ton appel de constructeur l.48

2017-05-14 15:32 UTC, aurelienCastellarnau commented on routes/cases.js
> +            case = new case(req.body)
Le nom du constructeur ne correspond pas à l'include.
Pour clarifier tout ca je propose 'Cases' ou 'Case' pour le nom du constructeur (et donc de l'include).

2017-05-14 15:32 UTC, aurelienCastellarnau commented on routes/cases.js
>        cases   = require('../models/casesModel');
Problème de nommage voir plus loin.

2017-05-14 15:35 UTC, Kumatetsu commented on routes/cases.js
> +    let case
j'suis déjà dessus :) je l'ai changé en newCase

2017-05-14 15:35 UTC, Kumatetsu commented on routes/cases.js
> +            case = new case(req.body)
oui c'est une idée que j'avais aussi de passer tous les constructs en Majuscule sur la première lettre

2017-05-14 16:08 UTC, aurelienCastellarnau commented on routes/cases.js
> +router.post("/:id/edit", function(req, res){
ici on ferait plutôt un router.put('/:id', callback);
comme ça tu sais que c'est un update grâce au put, et plus besoin du '/edit'

2017-05-14 16:11 UTC, aurelienCastellarnau commented on routes/agents.js
> +router.post("/create", function (req, res){
on peut se débarasser du '/create' en identifiant la création d'une entité par le mot clé post.
pour ça, il faudrait qu'on attribue le put à l'update.

2017-05-15 22:37 UTC, aurelienCastellarnau approved these changes
Ca marche impeccable avec postman, j'ai jeter un oeil côté implémentation front, tu vas t'en sortir... pr au top, on à l'api qui tourne et qui est token Protected!

2017-05-15 22:39 UTC, merged